Configure PyGlslang builds
UniversityOfGdanskTeamPython/pyglslang pull request #6
Opened 2023-11-10 20:28 UTC by MatSzpy

Related-to: #2

2023-11-10 22:41 UTC, Argmaster submitted a review, later dismissed

2023-11-16 00:42 UTC, Argmaster commented on src/pyglslang/api.py
> +    """Compile shader."""
![iuy9fxt300811](https://github.com/UniversityOfGdanskTeamPython/pyglslang/assets/56170852/50b11efb-3221-4fd5-9093-1b766d3ccf5a)

2023-11-16 19:13 UTC, Ave44 approved these changes, later dismissed

2023-11-16 20:12 UTC, mateuszzalewski011 submitted a review, later dismissed

2023-11-17 22:00 UTC, Argmaster requested changes

2023-11-17 22:00 UTC, Argmaster commented on src/pyglslang/api.py
> +    temp = tempfile.NamedTemporaryFile(name="temp_result", dir="~/pyglslang/src/pyglslang")
Leaving `~` in here may not work on windows, I also do not understand why are you specifying non-default directory for this temporary file?

To be honest I don't understand this code at all. Why are you storing stdout of glslang but you are neither specifying output file path, nor providing some known cwd for glslang to access output file. 
And of course you are not reading compiled SPIR-V from file created by glslang.

2023-11-17 22:00 UTC, Argmaster commented on src/pyglslang/compiler_options.py
> +        params: list[str] = ["glslang"]
I'd recomment removing `glslang` from here, so the list contains only params themselves, glslang executable path can be added later on.

2023-11-17 22:00 UTC, Argmaster commented on src/pyglslang/compiler_results.py
> +        test = subprocess.check_output(test_glsl)
From python documentation for `subprocess.check_output()`

> Run command with arguments and return its output.

I don't think it is what you want. You should be storing CompletedProcess object returned by `subprocess.run` which invoked `glslang` instead. Then you'd be able to check if `result.returncode` is equal to `0`. Programs tend to return `0` when they succeed and non-zero code when they fail.

2023-11-17 22:00 UTC, Argmaster commented on src/pyglslang/api.py
> +    result = subprocess.run(params, capture_output=True)
```suggestion
    glslang_executable_path = get_glslang_executable_path()
    result = subprocess.run([glslang_executable_path, *params], executable=glslang_executable_path, capture_output=True)
```

2023-11-27 21:33 UTC, closed without merging